apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra-e2e-dc1-rack1
status:
  currentReplicas: 1
  replicas: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra-e2e-dc1-rack2
status:
  currentReplicas: 1
  replicas: 1
---
apiVersion: db.orange.com/v1alpha1
kind: CassandraCluster
metadata:
  name: cassandra-e2e
spec:
  nodesPerRacks: 1
  topology:
    dc:
      - name: dc1
        rack:
          - name: rack1
          - name: rack2
status:
  lastClusterAction: ScaleDown
  lastClusterActionStatus: Done
  phase: Running
